sudo: false
language: node_js
node_js:
  - "7"
  - "6"
matrix:
  fast_finish: true
before_script:
  - npm install babel-eslint
  - wget https://github.com/mgreter/sass2scss/archive/v1.0.5.tar.gz
  - tar zxf v1.0.5.tar.gz
  - cd sass2scss-1.0.5/
  - make
  - cd ..
  - export PATH=$PATH:$PWD/sass2scss-1.0.5
  - sass2scss --version

script:
  - npm run lint
  - npm test
