sudo: false
language: node_js
node_js:
  - "8"
matrix:
  fast_finish: true
before_script:
  - npm install babel-eslint
  - wget https://github.com/mgreter/sass2scss/archive/v1.1.2.tar.gz
  - tar zxf v1.1.2.tar.gz
  - cd sass2scss-1.1.2/
  - make
  - cd ..
  - export PATH=$PATH:$PWD/sass2scss-1.1.2
  - sass2scss --version

script:
  - npm run lint
  - npm test
